const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
const vm=require('node:vm');
function load(file,mocks={},extra={}) {const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{exports,require:(name)=>mocks[name]||require(name),TextEncoder,btoa,Response,AbortSignal,...extra});return exports;}
const mail=load('lib/mail.ts');
test('MIME preserves unicode, encodes body and rejects header injection',()=>{const raw=mail.makeRaw('hello@example.com','A café website','Hello café');const mime=Buffer.from(raw,'base64url').toString();assert.match(mime,/Content-Transfer-Encoding: base64/);assert.equal(Buffer.from(mime.split('\r\n\r\n')[1],'base64').toString(),'Hello café');assert.throws(()=>mail.makeRaw('a@example.com\r\nBcc:x@y.com','hi','body'));assert.throws(()=>mail.makeRaw('a@example.com','hi\r\nBcc:x@y.com','body'));});
function harness(mode='success',blocked=false){let calls=0;const states=new Map();const deliveries={async reserve(id){if(states.has(id))return false;states.set(id,'uncertain');return true;},async complete(id,status){if(states.get(id)==='uncertain')states.set(id,status);}};const server={guard:async()=>{if(blocked)throw Error('unauthorized')},json:(d,s=200)=>Response.json(d,{status:s}),failure:(e,message)=>Response.json({error:message},{status:blocked?401:503})};const route=load('app/api/send/route.ts',{'@/lib/server':server,'@/lib/database':{deliveries},'@/lib/mail':mail,'@/lib/catalog':{getLeads:()=>[{id:1,status:'ready',email:'a@example.com',subject:'Hi',body:'Hello'},{id:2,status:'sent'}]}},{fetch:async(url)=>{if(url.includes('userinfo'))return Response.json({email:mode==='wrong'?'wrong@example.com':mail.sender,verified_email:true});calls++;if(mode==='timeout')throw Error('timeout');return mode==='failure'?new Response('',{status:429}):Response.json({id:'message-123'});}});return{send:(id=1)=>route.POST({json:async()=>({id,token:'fake-test-token'})}),states,get calls(){return calls}};}
test('successful send is persisted and repeat click does not resend',async()=>{const h=harness();assert.equal((await h.send()).status,200);assert.equal(h.states.get(1),'sent');assert.equal((await h.send()).status,409);assert.equal(h.calls,1);});
test('uncertain sends are not retried',async()=>{const h=harness('timeout');assert.equal((await h.send()).status,503);assert.equal(h.states.get(1),'uncertain');assert.equal((await h.send()).status,409);assert.equal(h.calls,1);});
test('wrong Gmail account cannot send',async()=>{const h=harness('wrong');assert.equal((await h.send()).status,403);assert.equal(h.calls,0);});
test('unauthenticated requests cannot send',async()=>{const h=harness('success',true);assert.equal((await h.send()).status,401);assert.equal(h.calls,0);});
test('Gmail rate-limit rejection recorded without retry',async()=>{const h=harness('failure');assert.equal((await h.send()).status,502);assert.equal(h.states.get(1),'failed');assert.equal((await h.send()).status,409);assert.equal(h.calls,1);});
test('historical sent and bounced records remain blocked',()=>{const leads=JSON.parse(fs.readFileSync('lib/leads.json'));assert.equal(leads.length,100);assert.equal(leads.filter(l=>l.status==='ready').length,66);assert.equal(leads.find(l=>l.id===2).status,'sent');assert.equal(leads.find(l=>l.id===4).status,'sent');assert.equal(leads.find(l=>l.id===6).status,'bounced');for(const l of leads.filter(l=>l.status==='ready')){assert.ok(l.body.includes(l.business));assert.ok(l.body.includes('https://aston-rodrigues.vercel.app/'));assert.ok(l.evidence);}});
test('concurrent clicks cause only one send',async()=>{const h=harness();const r=await Promise.all([h.send(),h.send()]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);assert.equal(h.calls,1);});
test('historical sent ID is rejected on the server',async()=>{const h=harness();assert.equal((await h.send(2)).status,400);assert.equal(h.calls,0);});
